INSERT INTO `estado` (`id`, `Nome`, `Sigla`, `created_at`, `updated_at`) VALUES (NULL, 'Mato Grosso', 'MT', NULL, NULL);

INSERT INTO `cat_ingredientes` (`id`, `Nome`, `Obs`, `created_at`, `updated_at`) VALUES (NULL, 'ALIMENTOS IN NATURA E MINIMAMENTE PROCESSADOS', NULL, NULL, NULL);    INSERT INTO `cat_ingredientes` (`id`, `Nome`, `Obs`, `created_at`, `updated_at`) VALUES (NULL, 'ALIMENTOS PROCESSADOS', NULL, NULL, NULL);
INSERT INTO `cat_ingredientes` (`id`, `Nome`, `Obs`, `created_at`, `updated_at`) VALUES (NULL, 'ALIMENTOS PROCESSADOS', NULL, NULL, NULL);
INSERT INTO `cat_ingredientes` (`id`, `Nome`, `Obs`, `created_at`, `updated_at`) VALUES (NULL, 'ALIMENTOS ULTRAPROCESSADOS', NULL, NULL, NULL);
INSERT INTO `cat_ingredientes` (`id`, `Nome`, `Obs`, `created_at`, `updated_at`) VALUES (NULL, 'INGREDIENTES CULINÁRIOS', NULL, NULL, NULL);
INSERT INTO `cat_ingredientes` (`id`, `Nome`, `Obs`, `created_at`, `updated_at`) VALUES (NULL, 'ALIMENTOS PROIBIDOS', NULL, NULL, NULL);

INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ACORIZAL', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ÁGUA BOA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ALTA FLORESTA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ALTO ARAGUAIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ALTO BOA VISTA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ALTO GARÇAS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ALTO PARAGUAI', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ALTO TAQUARI', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'APIACÁS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ARAGUAIANA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ARAPUTANGA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ARENÁPOLIS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ARIPUANÃ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'BARÃO DE MELGAÇO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'BARRA DO BUGRES', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'BARRA DO GARÇAS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'BOM JESUS DO ARAGUAIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'BRASNORTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CÁCERES', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CAMPINÁPOLIS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CAMPO NOVO DO PARECIS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CAMPO VERDE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CAMPOS DE JÚLIO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CANABRAVA DO NORTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CANARANA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CARLINDA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CASTANHEIRA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CHAPADA DOS GUIMARÃES', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CLÁUDIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'COCALINHO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'COLÍDER', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'COLNIZA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'COMODORO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CONFRESA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CONQUISTA D OESTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'COTRIGUAÇU', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CUIABÁ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'CURVELÂNDIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'DENISE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'DIAMANTINO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'DOM AQUINO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'FELIZ NATAL', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'FIGUEIRÓPOLIS DOESTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'GAÚCHA DO NORTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'GENERAL CARNEIRO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'GLÓRIA DOESTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'GUARANTÃ DO NORTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'GUIRATINGA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'INDIAVAÍ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'IPIRANGA DO NORTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ITANHANGÁ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ITAÚBA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ITIQUIRA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'JACIARA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'JANGADA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'JAURU', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'JUARA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'JUÍNA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'JURUENA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'JUSCIMEIRA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'LAMBARI DOESTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'LUCAS DO RIO VERDE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'LUCIÁRA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'MARCELÂNDIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'MATUPÁ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'MIRASSOL DOESTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOBRES', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NORTELÂNDIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOSSA SENHORA DO LIVRAMENTO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA BANDEIRANTES', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA BRASILÂNDIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA CANAÃ DO NORTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA GUARITA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA LACERDA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA MARILÂNDIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA MARINGÁ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA MONTE VERDE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA MUTUM', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA NAZARÉ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA OLÍMPIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA SANTA HELENA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA UBIRATÃ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVA XAVANTINA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVO HORIZONTE DO NORTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVO MUNDO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVO SANTO ANTÔNIO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'NOVO SÃO JOAQUIM', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PARANAÍTA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PARANATINGA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PEDRA PRETA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PEIXOTO DE AZEVEDO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PLANALTO DA SERRA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'POCONÉ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PONTAL DO ARAGUAIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PONTE BRANCA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PONTES E LACERDA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PORTO ALEGRE DO NORTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PORTO DOS GAÚCHOS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PORTO ESPERIDIÃO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PORTO ESTRELA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'POXORÉU', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'PRIMAVERA DO LESTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'QUERÊNCIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'RESERVA DO CABAÇAL', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'RIBEIRÃO CASCALHEIRA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'RIBEIRÃOZINHO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'RIO BRANCO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'RONDOLÂNDIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'RONDONÓPOLIS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'ROSÁRIO OESTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SALTO DO CÉU', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SANTA CARMEM', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SANTA CRUZ DO XINGU', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SANTA RITA DO TRIVELATO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SANTA TEREZINHA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SANTO AFONSO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SANTO ANTÔNIO DE LEVERGER', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SANTO ANTÔNIO DO LESTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SÃO FÉLIX DO ARAGUAIA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SÃO JOSÉ DO POVO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SÃO JOSÉ DO RIO CLARO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SÃO JOSÉ DO XINGU', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SÃO JOSÉ DOS QUATRO MARCOS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SÃO PEDRO DA CIPA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SAPEZAL', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SERRA NOVA DOURADA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SINOP', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'SORRISO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'TABAPORÃ', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'TANGARÁ DA SERRA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'TAPURAH', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'TERRA NOVA DO NORTE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'TESOURO', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'TORIXORÉU', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'UNIÃO DO SUL', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'VALE DE SÃO DOMINGOS', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'VÁRZEA GRANDE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'VERA', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'VILA BELA DA SANTÍSSIMA TRINDADE', '1', NULL, NULL);
INSERT INTO `cidade` (`id`, `Nome`, `estado_id`, `created_at`, `updated_at`) VALUES (NULL, 'VILA RICA', '1', NULL, NULL);

INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Alta Floresta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Barra do Garças', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Cáceres', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Confresa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Cuiabá', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Várzea Grande', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Diamantino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Juína', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Matupá', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Pontes e Lacerda', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Primavera do Leste', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Rondonópolis', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Sinop', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dre` (`id`, `Nome`, `Tel`, `Email`, `Endereco`, `Numero`, `Bairro`, `Cep`, `created_at`, `updated_at`) VALUES (NULL, 'DRE - Tangará da Serra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Abacaxi', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Abóbora cabotiã', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Abóbora paulista', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Abobrinha verde', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Açafrão', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Acelga', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Agrião', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Alface ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Alho branco', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Almeirão', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Amendoim ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Amido de milho', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Araruta ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Arroz branco', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Banana da terra', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Batata doce', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Batata inglesa', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Beiju ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Beterraba', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Biribá', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Brócolis', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Cará ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Carne bovina de 1ª acém (moída, cubos ou iscas)', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Carne bovina de 1ª músculo (moída, cubos ou iscas)', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Carne bovina de 1ª paleta (cubos ou iscas)', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Carne suína (lombo)', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Carne suína (paleta)', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Cebola branca', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Cebolinha', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Cenoura', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Chuchu', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Coentro', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Colorau', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Couve', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Coxa e sobrecoxa de frango', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Coxinhas das asas', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Farinha de arroz', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Farinha de mandioca', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Farinha de mandioca tipo puba', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Farinha de milho', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Farinha de trigo', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Feijão carioca', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Feijão em fava ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Feijão preto', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Fermento biológico', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Fermento químico', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Filé de peito', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Folha de taioba', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Fubá  mimoso', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Inhame', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Laranja', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Leite pasteurizado integral', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Limão ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Maçã', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Macarrão ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Mamão', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Mandioca', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Mangaba ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Mangarito', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Maracujá', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Massa para lasanha', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Massa para tapioca', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Melancia', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Milho em grãos ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Milho verde in natura', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Murici', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Orégano', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Ovo de galinha tipo A', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Peito de frango', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Peixe ', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Pepino', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Pimenta de cheiro', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Pimentão verde', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Polvilho azedo', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Polvilho doce', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Repolho branco', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Rúcula', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Salsa', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Tomate salada', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Trigo para quibe', NULL, NULL, '1', NULL, NULL);
INSERT INTO `produtos` (`id`, `Nome`, `Obs`, `image`, `cat_ingredientes_id`, `created_at`, `updated_at`) VALUES (NULL, 'Vagem', NULL, NULL, '1', NULL, NULL);